In [2]:
import numpy as np

In [10]:
nfold = 4
ntrain = 4
ntest = 2
number_labels = 3

In [8]:
oof_train = np.zeros((ntrain, number_labels))
oof_train

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
oof_train[[0,1]] = np.ones((2,3))

In [38]:
oof_train

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
oof_test = np.zeros((ntest, number_labels))
oof_test

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
oof_test_skf = np.empty((nfold, ntest, number_labels))
oof_test_skf.shape

(4, 2, 3)

In [13]:
clfpred1te = np.ones((1,3))
clfpred2te = np.ones((1,3))
clfpred3te = np.ones((1,3))
clfpred4te = np.ones((1,3))

In [23]:
clfpred1x_test = np.ones((2,3))
clfpred2x_test = np.ones((2,3))*2
clfpred3x_test = np.ones((2,3))*3
clfpred4x_test = np.ones((2,3))*4

In [27]:
oof_test_skf[0, :, :] = clfpred1x_test

In [28]:
oof_test_skf[1, :, :] = clfpred2x_test

In [29]:
oof_test_skf[2, :, :] = clfpred3x_test

In [30]:
oof_test_skf[3, :, :] = clfpred4x_test

In [31]:
oof_test_skf[:, :, :]

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[2., 2., 2.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [3., 3., 3.]],

       [[4., 4., 4.],
        [4., 4., 4.]]])

In [32]:
oof_test.shape

(2, 3)

In [33]:
oof_test[:] = oof_test_skf.mean(axis=0)

In [34]:
oof_test

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])