In [8]:
import pandas as pd
import numpy as np

In [7]:
# prediction
df_test_raw = pd.read_csv('/home/kai/data/kaggle/talkingdata/data/test.csv')
print('loading raw file done!')

pred_file = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/test/result/layer2/test_layer2_count_2_param0.npy'
pred = np.load(pred_file)
print(len(pred))
print('loading preds done!')

df_sub = pd.DataFrame()
df_sub['click_id'] = df_test_raw['click_id']
df_sub['is_attributed'] = pred
print('predicting file done!')

df_sub.to_csv('/home/kai/data/kaggle/talkingdata/wl/data/submission/layer2_count_2_param0.csv.gz', compression='gzip', index=False)
print('saving done')

loading raw file done!
18790469
loading preds done!
predicting file done!
saving done


In [4]:
pred_file1 = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/test/result/layer2/test_layer2_count_0_param0.npy'
pred_file2 = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/test/result/layer2/test_layer2_count_1_param0.npy'
pred1 = np.load(pred_file1)
pred2 = np.load(pred_file2)

In [16]:
pred_file1 = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/train/result/train_fold1_predonfold0_count_1_param0.npy'
pred_file2 = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/train/result/train_fold2_predonfold0_count_1_param0.npy'
pred_file11 = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/test/result/test_fold1_count_1_param0.npy'
pred_file22 = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/test/result/test_fold2_count_1_param0.npy'
pred1 = np.load(pred_file1)
pred2 = np.load(pred_file2)
pred11 = np.load(pred_file11)
pred22 = np.load(pred_file22)


pred_file1_2 = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/train/result/train_fold1_predonfold2_count_1_param0.npy'
pred_file0_2 = '/home/kai/data/kaggle/talkingdata/wl/data/stacking/train/result/train_fold0_predonfold2_count_1_param0.npy'
pred1_2 = np.load(pred_file1_2)
pred0_2 = np.load(pred_file0_2)

In [10]:
pred1

array([ 0.84083457,  0.88749952,  0.68913344, ...,  0.27927335,
        0.00973109,  0.11579792])

In [11]:
pred2

array([ 0.55295129,  0.52871682,  0.7313227 , ...,  0.17069087,
        0.00525627,  0.1485903 ])

In [14]:
pred11

array([ 0.1340116 ,  0.21826789,  0.06634163, ...,  0.27305709,
        0.52775494,  0.05677935])

In [15]:
pred22

array([ 0.1292117 ,  0.1643421 ,  0.02788493, ...,  0.33488905,
        0.13714095,  0.37014573])

In [17]:
pred1_2

array([ 0.15529972,  0.30375554,  0.00416998, ...,  0.72798661,
        0.00940963,  0.18263341])

In [18]:
pred0_2

array([ 0.21343001,  0.20990797,  0.00294498, ...,  0.38032923,
        0.01026586,  0.39555908])